name: TSandLang
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - pip
  - python=3.10
  - click=7.1
  - python-dotenv>=0.5.1
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - torchvision
  - pytorch-cuda=12.1
  - matplotlib
  - lightning
  - torchmetrics=0.11.4
  - transformers=4.31.0
  - tokenizers>=0.13.3
  - tiktoken
  - tqdm
  - omegaconf
  - hydra
  - pickle
  - pip:
    - einops
    - seaborn
    - git+https://github.com/haotian-liu/LLaVA@a0bdc71
    - wandb 
    - openai
    - jsonargparse[all]
    - torchaudio
variables:
  USE_TORCH: 1